# file: roles/jmeter/install/vars/main.yml

jmeter_version: 2.13
jmeter_install_dir: "/opt/jmeter"
jmeter_archive: "apache-jmeter-{{ jmeter_version }}.tgz"
jmeter_extracted_dir: "apache-jmeter-{{ jmeter_version }}"
jmeter_home_dir: "{{ jmeter_install_dir }}/{{ jmeter_version }}"
jmeter_download_url: "https://archive.apache.org/dist/jmeter/binaries/{{ jmeter_archive }}"
